# Day - 7
## Numpy - Numerical Python

In [10]:
import numpy as np
b = np.array([[5,5,5],[3,4,5],[2,4,6]])
c = b.transpose()
type(b)

numpy.ndarray

## Numpy Practice Session

### Creating array using Numpy

In [3]:
import numpy as np
name = np.array(["asim", "ali"])


In [8]:
len(name)
name[:1]

array(['asim'], dtype='<U4')

In [9]:
len(name)
name[1:]

array(['ali'], dtype='<U4')

In [22]:
np.zeros(13) # zeros
np.ones(5)   # ones
np.empty(5) # Empty
np.arange(8) # Non - empty consecutive number
np.arange(2,8)   
np.arange(2,20,2)  # range of numbers with specific interval

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
# table
np.arange(2,22,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [28]:
# line space
np.linspace(0,100, num=8)

array([  0.        ,  14.28571429,  28.57142857,  42.85714286,
        57.14285714,  71.42857143,  85.71428571, 100.        ])

In [30]:
# specify your data type
np.ones(10, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## Array Functions

In [33]:
a = np.array([10,12,15,2,4,6,100,320,0.5,10.3])
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

In [36]:
b = np.array([10.2,3.4,53.6])
np.concatenate((a,b))

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ,  10.2,   3.4,  53.6])

## 2-D Array

In [38]:
a = np.array([[1,2,3,4,5,6,7],[1,2,3,4,5,6,7]])
a

array([[1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7]])

In [45]:
b = np.array([[0,9,3,4,5,6,7],[8,9,1,2,3,4,5]])
c = np.concatenate((a,b),axis=0)
c

array([[1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7],
       [0, 9, 3, 4, 5, 6, 7],
       [8, 9, 1, 2, 3, 4, 5]])

## More than 2 Diamenssion Array

In [48]:
d = np.array([[[0,1,3,2],[4,2,3,4]],[[0,1,3,4],[4,2,3,4]],[[1,3,4,5],[2,3,4,5]]])
d

array([[[0, 1, 3, 2],
        [4, 2, 3, 4]],

       [[0, 1, 3, 4],
        [4, 2, 3, 4]],

       [[1, 3, 4, 5],
        [2, 3, 4, 5]]])

In [50]:
# defining the number of diamensions
d.ndim

3

In [52]:
d.size # number of elements

24

In [53]:
d.shape

(3, 2, 4)

In [55]:
e = np.arange(6)
# reshape
e.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [57]:
e.sum()
a.mean()

np.float64(4.0)

## Numpy Practice

In [61]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [62]:
c = np.array([[1, 2], [3, 4]], dtype=np.complex128)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

# Matrix Product in Numpy

## Taking the Product of the Matrixes

In [76]:
A = np.arange(15).reshape(3,5)
B = np.arange(15).reshape(5,3)
C = A @ B # Multiplies the matrixes
C

array([[ 90, 100, 110],
       [240, 275, 310],
       [390, 450, 510]])

In [77]:
# Element wise product of the matrixes
A.dot(B)

array([[ 90, 100, 110],
       [240, 275, 310],
       [390, 450, 510]])

In [ ]:
A.min()
A.max()

np.int64(14)

## Mathematical Operations in the Numpy

In [93]:
np.exp(A)
np.sqrt(A)
A[::-1] # reversed
A.transpose()
A is B 

False

I haave made the chanag