# Numpy 
What is Numpy ?
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

Numpy Arrays Vs Python Sequences

* NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.
* The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.
* NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python's built-in sequences.
* A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

## Creating Numpy Array

In [ ]:
# np.array
import numpy as np

In [3]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


## 2D and 3D 

In [4]:
# 2D Array
twoD = np.array([[1, 2, 3], [4, 5, 6]])
print(twoD) 

[[1 2 3]
 [4 5 6]]


In [5]:
# 3D Array or a tensor
threeD = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(threeD)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


 ## In Numpy you can your own data type array


### 1. Creating Float Data Type array

In [6]:
np.array([1, 2, 3], dtype=float)

array([1., 2., 3.])

### 2. Complex Data Type

In [7]:
np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [9]:
# np.arange (start, stop, step)
a = np.arange(0, 10, 2)
a

array([0, 2, 4, 6, 8])

In [13]:
# reshape reshape(rows, columns)
np.arange(0, 20).reshape(4, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [14]:
# np.ones and np.zeros
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
# np.random(random) generates random numbers between 0 and 1
np.random.random((3, 4))

array([[0.84322648, 0.44968024, 0.416348  , 0.65435604],
       [0.56719031, 0.31257946, 0.91260634, 0.47352893],
       [0.03471845, 0.37619943, 0.31693767, 0.90010882]])

In [17]:
# np.linspace(start, stop, num) 'Linear space' returns evenly spaced numbers over a specified interval.
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [18]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Array Attributes

In [19]:
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [20]:
# 1. ndim
a1.ndim

1

In [21]:
# 2. shape
a2.shape

(3, 4)

In [24]:
# 3. size
a2.size

12

In [27]:
# 4. itemsize (Each item in the array has a size in bytes. This can be accessed by the itemsize attribute of an array.  )
a2.itemsize

8

In [26]:
# 5. dtype
a2.dtype

dtype('float64')

## Changing Data types

In [29]:
# astype() method is used to cast an array to a different data type.
a2.astype(float)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

## Array Operations 

In [30]:
a1 = np.arange(12).reshape(3, 4)
a2 = np.arange(12, 24).reshape(3, 4)

In [31]:
# scalar operations
a1 + 5
a2 * 2

array([[24, 26, 28, 30],
       [32, 34, 36, 38],
       [40, 42, 44, 46]])

In [33]:
# relational operations
a1 > 5
a1 == 5
a1 != 5

array([[ True,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True,  True,  True]])

In [34]:
# vector operations
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [35]:
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

## Array Functions

In [36]:
a1 = np.random.random((3,3))
a1 = np.round(a1*12)


In [37]:
np.max(a1)

np.float64(11.0)

In [38]:
np.min(a1)

np.float64(0.0)

In [40]:
np.max(a1, axis = 0) 
# This will return the maximum value of each column.
# 0 -> column-wise operation 1 -> row-wise operation

array([ 45.,   0., 242.])

## Statistical Operations

In [41]:
np.mean(a1)

np.float64(4.888888888888889)

In [42]:
np.median(a1)

np.float64(3.0)

In [43]:
np.std(a1) # Standard Deviation

np.float64(3.9283710065919304)

## Trigonometry Operations 

In [44]:
np.sin(a1)

array([[ 0.14112001,  0.        , -0.99999021],
       [-0.95892427,  0.98935825,  0.90929743],
       [ 0.14112001,  0.84147098, -0.99999021]])

## Dot Product of the Matrices

In [45]:
# dot product
a1 = np.arange(12).reshape(3, 4)
a2 = np.arange(12, 24).reshape(4, 3)

In [46]:
np.dot(a1, a2)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [47]:
# log and exponential
np.log(a1)

C:\Users\khan faiz\AppData\Local\Temp\ipykernel_18784\2617702441.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [48]:
np.exp(a1)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

## Round / ceil / Floor Operations 

In [52]:
np.round(np.random.random((3, 4))* 10)

array([[2., 6., 7., 2.],
       [8., 8., 8., 1.],
       [6., 6., 3., 5.]])

In [53]:
np.floor(np.random.random((3, 4))* 10)

array([[3., 8., 3., 3.],
       [4., 4., 4., 8.],
       [6., 6., 5., 8.]])

In [54]:
np.ceil(np.random.random((3, 4))* 10)

array([[1., 8., 2., 9.],
       [9., 5., 7., 4.],
       [5., 2., 3., 1.]])

## Indexing and Slicing 

In [60]:
a1[2,3]

np.int64(11)

In [65]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [66]:
# 3D array
a3[1, 1, 1]

np.int64(7)

In [70]:
a1 = np.arange(12)
a1[1:4]

array([1, 2, 3])

In [71]:
a2[2,:]

array([18, 19, 20])

In [72]:
a2[1:3, 1:3]

array([[16, 17],
       [19, 20]])

In [73]:
a2

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [75]:
a2[::2,::1]

array([[12, 13, 14],
       [18, 19, 20]])

In [77]:
a2[::1,::2]

array([[12, 14],
       [15, 17],
       [18, 20],
       [21, 23]])

In [89]:
a2[0:2,1:3]

array([[13, 14],
       [16, 17]])

In [94]:
# in case of 3D
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [97]:
a3[1,:,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [100]:
a3[1,::2,::2]

array([[ 9, 11],
       [15, 17]])

In [105]:
a3[1,1:2,0:3]

array([[12, 13, 14]])

In [106]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

## Iterating

In [107]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [108]:
a2

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [109]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [112]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [113]:
for i in a2:
    print(i)

[12 13 14]
[15 16 17]
[18 19 20]
[21 22 23]


In [114]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


## Reshaping

In [ ]:
# reshape


In [122]:
# Transpose
np.transpose(a2)
# Or 
a1.T

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
# ravel it reshapes the 3D array into 1D array.                                
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

## Stacking

In [125]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12, 24).reshape(3,4)

In [126]:
# horizontal stacking (Simply do ya do se ziyada arrays ko ek saath jorna)
np.hstack((a4, a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [127]:
# vertical stacking
np.vstack((a4, a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting

In [128]:
# hortizontal splitting (yeh simply do ya do se ziyada arrays ko horizontal tor pe split kar deta hai)
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [129]:
# vertical splitting
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]